version: "3.9"
services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$db_password # don't forget to export db_password=<password>
    ports: 
      - "5432:5432"
    networks: ["custom-net"]
    volumes:
      - pwm-db-volume:/var/lib/postgresql/data
  key-manager:
    environment:
      - WORD_LIST_PATH=/opt/bin/words.txt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$db_password
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=postgres
      - LOCAL_TEST=$LOCAL_TEST
    build: ./keys_manager/.
    ports:
      - "9090:9090"
    networks: ["custom-net"]
    depends_on: 
      - db
  pwm_authenticator:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$db_password
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=postgres
      - KEYS_MANAGER_HOST=key-manager:9090
      - LOCAL_TEST=$LOCAL_TEST
    build: ./pwm_authenticator/.
    ports:
      - "8080:8080"
    networks: ["custom-net"]
    depends_on:
    - db
    - key-manager
  pwm_db_init:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$db_password
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=postgres
      - KEYS_MANAGER_HOST=key-manager:9090
      - LOCAL_TEST=$LOCAL_TEST
    build: ./pwm_db_api/.
    networks: ["custom-net"]
    depends_on:
    - db
    - key-manager
  pwm_manager:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=$db_password
      - WORDS_FILENAME=/opt/bin/words.txt
      - AUTHENTICATOR_ADDRESS=http://pwm_authenticator:8080
    build: ./pwm_manager/.
    ports: ["8989:8989"]
    networks: ["custom-net"]
    depends_on:
    - db
    - pwm_authenticator

  gateway:
    environment:
      - PWM_MANAGER_HOSTNAME=pwm_manager:8989
    build: 
      context: ./gateway/
      dockerfile: ./build/Dockerfile
    ports: ["6969:6969"]
    networks: ["custom-net"]
    depends_on:
    - db
    - pwm_manager

volumes:
  pwm-db-volume: {}

networks: 
  custom-net: {}
