name: pwm-ci
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: securepassword
          POSTGRES_DB: postgres
        ports: 
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16 

    - name: build & running 
      run: cd keys_manager && go build -o service server/server.go && ./service

    - name: keys-manager-Test
      run: export POSTGRES_USER=postgres && \
           export POSTGRES_PASSWORD=securepassword && \
           export POSTGRES_DB=postgres && \
           go test -v ./keys_manager/keys_manager_testing/.
