name: pwm-ci
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: golang:1.16

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16 

    - name: build keys_manager
      run: cd keys_manager &&  go build -o service server/server.go

    - name: keys_manager testing
      run: cd keys_manager && go test -v ./keys_manager_testing/.

    - name: init database.
      run: cd pwm_db_api && go build -o script cmd/main.go && ./script

