name: pwm-ci
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16 

    - name: build keys_manager
      run: cd keys_manager && . init.sh &&  go build -o service server/server.go

    - name: keys_manager testing
      run: cd keys_manager && go test -v ./keys_manager_testing/.
